### PR TITLE
let user can set transactionId

### PR DESCRIPTION
**Pull request by linzx2015**

### CODE REVIEW

**Comment by terrypacker** [comment]
This code will break compatibility with how the TcpMaster is currently used in external applications by requiring a call to set the next transaction ID.  A better solution would be to provide an additional constructor with a boolean to indicate if the master should auto-increment the transaction ID or not.  By default the TcpMaster should auto-increment.

Then in the sendImpl one could key off of this and optionally increment and get the id or just get the existing one that presumably has been set before the call to sendImpl.

**Comment by terrypacker** [comment]
Can you provide a use case for why you need to set the transaction ID?  If it is convincing enough I will code up the solution for you.

**Comment by linzx2015** [comment]
@terrypacker In my project, I use the sensor transactionId is 0x1501, because modbus4j in the transactionId default is 0, so I need to cycle call 1501 getNextTransactionId () in order to change the transactionId required 0x1501, so I hope to be able to manually set trasactionId.

**Comment by terrypacker** [comment]
Closing this and implemented via commit 444e51be1847dfbd87ecaeb00aa2201794a2fc1b

**Pull request closed without merging**
